# Generated by Django 4.2 on 2025-04-08 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agendamento',
            old_name='data',
            new_name='data_hora',
        ),
    ]
