# Generated by Django 4.2 on 2025-04-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='medico',
            name='especialidade',
            field=models.CharField(choices=[('clinico', 'Clínico Geral'), ('cardiologista', 'Cardiologista'), ('dermatologista', 'Dermatologista'), ('pediatra', 'Pediatra'), ('ortopedista', 'Ortopedista'), ('car', 'CAR')], max_length=100),
        ),
    ]
